# Generated by Django 4.1.5 on 2023-01-16 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
    ]
